on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and tag Docker image
        run: |
         sudo docker build -t python-app .
  deploy:
    runs-on: [self-hosted]
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/daidoan/auto
            sudo docker-compose down
            sudo docker-compose up -d
